
import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';

export const generatePDF = async (quizResults: any, calculatorResults: any) => {
  const pdf = new jsPDF('p', 'mm', 'a4');
  const pageWidth = pdf.internal.pageSize.getWidth();
  const pageHeight = pdf.internal.pageSize.getHeight();
  
  // Header
  pdf.setFontSize(24);
  pdf.setFont('helvetica', 'bold');
  pdf.text('Identity ROI Analysis Report', pageWidth / 2, 30, { align: 'center' });
  
  // Date
  pdf.setFontSize(12);
  pdf.setFont('helvetica', 'normal');
  const currentDate = new Date().toLocaleDateString();
  pdf.text(`Generated on: ${currentDate}`, pageWidth / 2, 40, { align: 'center' });
  
  let yPosition = 60;
  
  // Overall Grade
  pdf.setFontSize(18);
  pdf.setFont('helvetica', 'bold');
  pdf.text('Identity Health Scorecard', 20, yPosition);
  yPosition += 15;
  
  pdf.setFontSize(14);
  pdf.text(`Overall Grade: ${quizResults.overallGrade}`, 20, yPosition);
  pdf.text(`Score: ${quizResults.overallScore.toFixed(1)}/4.0`, 120, yPosition);
  yPosition += 20;
  
  // Category Scores
  pdf.setFontSize(12);
  pdf.setFont('helvetica', 'bold');
  pdf.text('Category Breakdown:', 20, yPosition);
  yPosition += 10;
  
  pdf.setFont('helvetica', 'normal');
  Object.entries(quizResults.scores).forEach(([category, data]: [string, any]) => {
    const categoryName = getCategoryName(category);
    pdf.text(`${categoryName}: ${data.grade} (${data.score.toFixed(1)}/4.0)`, 25, yPosition);
    yPosition += 8;
  });
  
  yPosition += 15;
  
  // Revenue Impact
  pdf.setFontSize(18);
  pdf.setFont('helvetica', 'bold');
  pdf.text('Revenue Impact Analysis', 20, yPosition);
  yPosition += 15;
  
  pdf.setFontSize(12);
  pdf.setFont('helvetica', 'normal');
  
  const formatCurrency = (amount: number) => {
    return new Intl.NumberFormat('en-US', {
      style: 'currency',
      currency: 'USD',
      minimumFractionDigits: 0,
      maximumFractionDigits: 0
    }).format(amount);
  };
  
  pdf.text(`Monthly Revenue Loss: ${formatCurrency(calculatorResults.darkInventory.lostRevenue)}`, 20, yPosition);
  yPosition += 8;
  pdf.text(`Monthly Uplift Potential: ${formatCurrency(calculatorResults.uplift.totalMonthlyUplift)}`, 20, yPosition);
  yPosition += 8;
  pdf.text(`Annual Opportunity: ${formatCurrency(calculatorResults.uplift.totalAnnualUplift)}`, 20, yPosition);
  yPosition += 8;
  pdf.text(`Revenue Improvement: +${calculatorResults.uplift.percentageImprovement.toFixed(1)}%`, 20, yPosition);
  yPosition += 8;
  pdf.text(`Match Rate Improvement: +${calculatorResults.breakdown.matchRateImprovement}%`, 20, yPosition);
  yPosition += 20;
  
  // Key Metrics
  pdf.setFontSize(14);
  pdf.setFont('helvetica', 'bold');
  pdf.text('Key Metrics:', 20, yPosition);
  yPosition += 10;
  
  pdf.setFontSize(12);
  pdf.setFont('helvetica', 'normal');
  pdf.text(`Dark Inventory: ${calculatorResults.darkInventory.percentage.toFixed(1)}%`, 25, yPosition);
  yPosition += 8;
  pdf.text(`Current Match Rate: ${calculatorResults.inputs.currentMatchRate}%`, 25, yPosition);
  yPosition += 8;
  pdf.text(`Monthly Pageviews: ${new Intl.NumberFormat('en-US').format(calculatorResults.inputs.monthlyPageviews)}`, 25, yPosition);
  yPosition += 20;
  
  // Recommendations
  if (yPosition > pageHeight - 60) {
    pdf.addPage();
    yPosition = 30;
  }
  
  pdf.setFontSize(14);
  pdf.setFont('helvetica', 'bold');
  pdf.text('Key Recommendations:', 20, yPosition);
  yPosition += 10;
  
  pdf.setFontSize(12);
  pdf.setFont('helvetica', 'normal');
  
  const recommendations = [];
  if (quizResults.overallScore < 3.0) {
    recommendations.push('• Implement a comprehensive identity resolution strategy');
  }
  if (quizResults.scores['browser']?.score < 2.5) {
    recommendations.push('• Optimize for Safari and privacy-focused browsers');
  }
  if (quizResults.scores['cross-domain']?.score < 2.5) {
    recommendations.push('• Improve cross-domain identity resolution capabilities');
  }
  if (quizResults.scores['privacy']?.score < 3.0) {
    recommendations.push('• Strengthen privacy compliance and consent management');
  }
  
  recommendations.forEach(rec => {
    pdf.text(rec, 25, yPosition);
    yPosition += 8;
  });
  
  // Footer
  pdf.setFontSize(10);
  pdf.setFont('helvetica', 'italic');
  pdf.text('Generated by AdFixus ID Simulator', pageWidth / 2, pageHeight - 15, { align: 'center' });
  
  return pdf;
};

const getCategoryName = (category: string) => {
  const names = {
    'durability': 'Identity Durability',
    'cross-domain': 'Cross-Domain Visibility',
    'privacy': 'Privacy & Compliance',
    'browser': 'Browser Resilience'
  };
  return names[category] || category;
};

export const sendPDFByEmail = async (pdfBlob: Blob, userEmail?: string) => {
  // Create FormData to send the PDF
  const formData = new FormData();
  formData.append('pdf', pdfBlob, 'identity-roi-report.pdf');
  formData.append('recipientEmail', 'krish.raja@adfixus.com');
  formData.append('userEmail', userEmail || 'Unknown');
  formData.append('timestamp', new Date().toISOString());
  
  try {
    // This would typically go to your backend endpoint
    // For now, we'll log the action and show a message to the user
    console.log('PDF would be sent to krish.raja@adfixus.com');
    console.log('PDF blob size:', pdfBlob.size);
    
    // In a real implementation, you would send this to your backend:
    // const response = await fetch('/api/send-pdf', {
    //   method: 'POST',
    //   body: formData,
    // });
    
    return { success: true, message: 'PDF sent successfully' };
  } catch (error) {
    console.error('Error sending PDF:', error);
    return { success: false, message: 'Failed to send PDF' };
  }
};
