// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from '../../types/supabase';
import { validateSupabaseConfig } from '@/utils/envValidation';

// Validate environment variables before creating client
let supabaseInstance: ReturnType<typeof createClient<Database>> | null = null;

function createSupabaseClient() {
  try {
    const config = validateSupabaseConfig();
    
    // Diagnostic logging
    if (import.meta.env.DEV) {
      console.log('[supabase/client] [DIAGNOSTIC] Initializing with URL:', config.url.substring(0, 50) + '...');
      console.log('[supabase/client] [DIAGNOSTIC] Key length:', config.key.length);
    }
    
    const client = createClient<Database>(config.url, config.key, {
      auth: {
        storage: localStorage,
        persistSession: true,
        autoRefreshToken: true,
        // Use default storage key for main client
        storageKey: 'supabase.auth.token',
      },
    });
    
    // Log actual client URL after creation
    if (import.meta.env.DEV) {
      try {
        const clientUrl = (client as any).supabaseUrl || (client as any).rest?.url;
        console.log('[supabase/client] [DIAGNOSTIC] Client URL after creation:', clientUrl ? clientUrl.substring(0, 50) + '...' : 'not available');
        console.log('[supabase/client] [DIAGNOSTIC] Edge function URL would be:', clientUrl ? `${clientUrl}/functions/v1/scan-domain` : 'not available');
      } catch (e) {
        // Ignore - diagnostic only
      }
      console.log('[supabase/client] Main Supabase client initialized successfully');
    }
    
    return client;
  } catch (error) {
    const errorMessage = error instanceof Error ? error.message : 'Unknown error';
    console.error('[supabase/client] Failed to initialize Supabase client:', errorMessage);
    
    // In development, throw to catch configuration issues early
    if (import.meta.env.DEV) {
      throw error;
    }
    
    // In production, create a dummy client that will fail gracefully
    // This prevents the app from crashing, but operations will fail
    return createClient<Database>('https://invalid.supabase.co', 'invalid-key', {
      auth: {
        persistSession: false,
        autoRefreshToken: false,
      },
    });
  }
}

// Singleton pattern - ensure client is only created once
export const supabase = (() => {
  if (!supabaseInstance) {
    supabaseInstance = createSupabaseClient();
  }
  return supabaseInstance;
})();

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";